language: python
python:
  - "2.7"
env:
  - TEST=1
install: pip install -r requirements-test.txt
before_script:
  - psql -U postgres -c 'create database ridesf_test;'
  - psql -U postgres -c "create extension postgis"
script:  nosetests tests/ --with-coverage
after_script:
  coveralls
